version: '3'
services:

  workspace:
    build:
      context: .
      args:
        - uid=${COMPOSE_UID:-1000}
        - gid=${COMPOSE_GID:-995} #995 is my docker-group, and I ran `sudo chmod g+w /var/run/docker.sock`. Get docker group: `getent group docker | cut -d: -f3`
    security_opt: ['label:disable']
    volumes:
      - ../:/workspace:Z
      - ../.vscode-server:/home/developer/.vscode-server:Z
      - ~/.gitconfig:/home/developer/.gitconfig:ro,z
      - ~/.ssh:/home/developer/.ssh:z
      - /var/run/docker.sock:/var/run/docker.sock #to run pandoc from inside this container
      - /usr/bin/docker:/usr/bin/docker           #to run pandoc from inside this container
      - ../pandoc_markdown_base:/opt/input_data
      - ../pandoc_generated_latex:/opt/output_data
    command: sleep infinity
    environment:
      - PAR_GLOBAL_TEMP=/workspace/tmp
    user: "${uid}:${gid}" 
    privileged: true #such that I can call the other container from inside, see (https://forums.docker.com/t/execute-command-from-a-container-to-another-container/19492/5) (BAD IDEA!!)

  pandoc:
    image: pandoc/latex
    volumes:
      - ../pandoc_markdown_base:/opt/input_data
      - ../pandoc_generated_latex:/opt/output_data
    entrypoint: /bin/sh -c 'while sleep 3600; do :; done'
    container_name: mastersthesistext_devcontainer_pandoc_1