name: Create PDF

on: 
  push:
  workflow_dispatch:

jobs:
  create_pdf:
    name: Create & Add PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # repo now available under $GITHUB_WORKSPACE
      - name: Create PDF inside container
        shell: bash
        run: |
          docker-compose -f .devcontainer/docker-compose.yml run workspace bash /workspace/.devcontainer/create_pdf.sh
        env:
            COMPOSE_UID: 1001
            COMPOSE_GID: 121
      - name: Upload created pdf
        uses: actions/upload-artifact@v2
        with:
          name: Thesis
          path: thesis.pdf
          job_alias: latest
      - name: Help post checkout 
        shell: bash
        run: |
          rmdir /home/runner/.gitconfig
          touch /home/runner/.gitconfig
