name: Create PDF

on: 
  push:
  workflow_dispatch:

jobs:
  create_pdf:
    name: Create & Add PDF
    runs-on: ubuntu-latest
    env: 
      workdir: .
    steps:
      - uses: actions/checkout@v2 # repo now available under $GITHUB_WORKSPACE
      - name: Create Pandoc-Container
        run: docker-compose -f .devcontainer/docker-compose.yml up -d
      - name: Compile Pandoc
        run: |
          docker ps -a
          docker exec mastersthesistext_devcontainer_pandoc_1 pwd
          for s in $(ls pandoc_markdown_base/); do docker exec mastersthesistext_devcontainer_pandoc_1 pandoc --listings -t latex /opt/input_data/$s -o /opt/output_data/$(echo $s | sed 's/.md/.tex/g'); done
        working-directory: ${{env.workdir}}
      - name: Create PDF inside container
        shell: bash
        run: |
          docker-compose -f .devcontainer/docker-compose.yml run workspace bash /workspace/.devcontainer/create_pdf.sh
          docker-compose -f .devcontainer/docker-compose.yml run workspace latexmk -r /workspace/.latexmkrc -synctex=1 -interaction=nonstopmode -file-line-error -pdf -outdir=/workspace /workspace/thesis_nomarkdown.tex
          docker-compose -f .devcontainer/docker-compose.yml run workspace latexmk -r /workspace/.latexmkrc -synctex=1 -interaction=nonstopmode -file-line-error -pdf -outdir=/workspace /workspace/thesis_forprinting.tex
        env:
            COMPOSE_UID: 1001
            COMPOSE_GID: 121
      - name: Upload created pdf
        uses: actions/upload-artifact@v3
        with:
          name: Thesis
          path: |
            thesis.pdf
            thesis_forprinting.pdf
            thesis_nomarkdown.pdf
      - name: Help post checkout 
        shell: bash
        run: |
          rmdir /home/runner/.gitconfig
          touch /home/runner/.gitconfig
